type User {
    # id: ID! @unique
    firstName: String!
    lastName: String!
    username: String! @unique
    email: String! @unique
    password: String!
    verified: Boolean
    clubs: [Club!]
}

type Book {
    # id: ID! @unique
    name: String!
    author: String!
    tags: [Tag!]! @relation
    available: Boolean
    clubs: [Club!] @relation(name: "previously_read")
}

type Club {
    # id: ID! @unique
    name: String! @unique
    members: [User!]!
    currentBook: Book! @relation 
    prevBooks: [Book!]! @relation(name: "previously_read")
    creationDate: Time!
}

type Discussion {
    # id: ID! @unique
    text: String!
    comments: [Comment!]! @relation
    tags: [Tag!] @relation
    creationDate: Time!
}

type Comment {
    # id: ID! @unique
    text: String!
    discussion: Discussion! @relation
    tags: [Tag!] @relation
    creationDate: Time!
}

type Tag {
    # id: ID! @unique
    name: String!
    books: [Book!] @relation
    comments: [Comment!] @relation
    discussions: [Discussion!] @relation
}

type Query {
    allUsers: [User!] @index(name: "all_users")
    allClubs: [Club!] @index(name: "all_clubs")
    allBooks: [Book!] @index(name: "all_books")
    allTags: [Tag!] @index(name: "all_tags")
    allDiscussion: [Discussion!] @index(name: "all_discussions")
    allComments: [Comment!] @index(name: "all_comments")
}
